export interface Appointments{
    $key: string;
    customerName;
    callDate;
    address;
    locality;
    phone;
    visitType;
    staff;
    productType;
    brand;
    appointmentDate;
    appointmentTime;
    status;
    svcCharge;
    spares;
    sparesTotal;
    totalAmount;
    rcNo;
    cashRcvDate;
    cashRcvDateStr;
    dueDays;
    // employeeName;
    // svcDate;
    // customerName;
    // address;
    // area;
    // phone;
    // product;
    // productType;
    // visitType;
    // svcCharge;
    // spareName;
    // spareAmount;
    // amount;
    // rcNo;
    // cashRcvDate;
    // tecServCharges;
    // tecSpareCharges;
    // cashAdvance;
    // expenses;
    // status;
}